import { useState } from 'react';
import { Card } from '../components/common/Card';
import { StatCard } from '../components/common/StatCard';
import { bookings } from '../mocks/bookings';

export function AdvisorDashboardPage() { return <div className="stack-lg"><h1>Advisor Dashboard</h1><div className="grid cols-4"><StatCard label="Profile completion" value="86%"/><StatCard label="Upcoming bookings" value="6"/><StatCard label="Availability health" value="Strong"/><StatCard label="Revenue (placeholder)" value="$12,300"/></div><Card><h3>Pending tasks</h3><ul><li>Complete trust indicators</li><li>Update next-week availability</li></ul><div className="stack-row"><button className="btn">Edit Profile</button><button className="btn ghost">Manage Availability</button></div></Card></div>; }

export function AdvisorProfileEditorPage() { const sections=['Identity','Positioning','Executive background','Industries/functions','Advisory topics','Achievements','Case studies','Session offerings','Trust indicators']; return <div className="stack-lg"><h1>Profile Editor</h1>{sections.map((s)=><Card key={s}><h3>{s}</h3><p className="muted">Provide clear, evidence-backed details to build buyer trust.</p><input placeholder={`${s} details`} /></Card>)}</div>; }

export function AdvisorAvailabilityPage() { return <div className="stack-lg"><h1>Availability Manager</h1><Card><label>Timezone<select><option>America/New_York</option><option>America/Los_Angeles</option></select></label></Card><Card><h3>Weekly Availability Grid</h3><p>Mon-Fri blocks with editable morning/afternoon/evening slots.</p></Card><div className="grid cols-3"><Card><label>Slot duration<select><option>30 min</option><option>45 min</option><option>60 min</option></select></label></Card><Card><label>Buffer settings<select><option>15 min</option><option>30 min</option></select></label></Card><Card><label>Minimum notice<input defaultValue="24 hours"/></label></Card></div><Card><h3>Blackout dates & generated preview</h3><p>No-sync placeholder with preview of bookable times.</p></Card><Card><h3>External calendar busy-sync</h3><p className="muted">Placeholder for future Google/Microsoft busy-state sync.</p></Card></div>; }

export function AdvisorBookingsPage() { const [active] = useState('all'); return <div className="stack-lg"><h1>Advisor Bookings</h1><p className="muted">{active}</p><div className="grid cols-2">{bookings.map((b)=><Card key={b.id}><h4>{b.sessionName}</h4><p>{b.clientName}</p><p className="muted">Track prep notes, attendance, and post-session artifacts.</p></Card>)}</div></div>; }
